#!/bin/bash -ex

if [[ $# -lt 3 ]]; then
        echo "usage: $0 INPUT OUTPUT LANGUAGE [WORKER_COUNT] [DOCKERIMAGE]"
        exit 2
fi

INPUT="$(readlink -f $1)"
OUTPUT="$(readlink -f $2)"
LANGUAGE="$3"

if [[ -z "$4" ]]; then
        WORKER_COUNT=3
else
        WORKER_COUNT="$4"
fi

if [[ -z "$5" ]]; then
        IMG="liquidinvestigations/tesseract-batch"
        docker pull $IMG
else
        IMG="$5"
fi

exec docker run --user "$(id -u):$(id -g)" \
        -v $INPUT:/input \
        -v $OUTPUT:/output \
        -e "LANGUAGE=$LANGUAGE" \
        -e "WORKER_COUNT=$WORKER_COUNT" \
        $IMG
